version: '3.1'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4356
      - POSTGRES_DB=postgres

  web:
    build: ./
    container_name: tiwar
    restart: always
    ports:
      - 8080:8080

